on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - 'Makefile'
      - '.dockerignore'
      - '.gitignore'
      - 'LICENSE'
      - 'infra/**'
      - 'okteto-pipeline.yml'
  pull_request:
    paths-ignore:
      - '**.md'
      - 'Makefile'
      - '.dockerignore'
      - '.gitignore'
      - 'LICENSE'
      - 'infra/**'
      - 'okteto-pipeline.yml'
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  lint:
    runs-on: ubuntu-latest
    name: Run clippy
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v2
      - name: Setup rust toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Run clippy
        run: cargo clippy --all-targets --all-features -- -D warnings
  test:
    runs-on: ubuntu-latest
    name: Run test
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: Swatinem/rust-cache@v2
      - name: Setup rust toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Run test
        run: cargo test --all -- --nocapture

